# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-monit

# >> macros
# << macros
%define spectacle_bug hack_fix
%if 0%{?sailfishos_version} > 40300
BuildRequires:  pkgconfig(libcrypt)
%endif

Summary:    Sailfish OS GUI for monit
Version:    0.9.1
Release:    0
Group:      Applications
License:    ASL 2.0
BuildArch:  noarch
URL:        https://github.com:sailfishos-chum/monit
Source0:    %{name}-%{version}.tar.gz
Source100:  harbour-monit.yaml
Source101:  harbour-monit-rpmlintrc
Requires:   monit >= 5.24
Requires:   libsailfishapp-launcher
BuildRequires:  qt5-qttools-linguist
BuildRequires:  qt5-qmake
BuildRequires:  sailfish-svg2png
BuildRequires:  qml-rpm-macros
BuildRequires:  desktop-file-utils

%description
Monit. Barking at daemons.

Monit is a small Open Source utility for managing and monitoring Unix
systems. Monit conducts automatic maintenance and repair and can execute
meaningful causal actions in error situations.

This is a simple Sailfish OS GUI application to view the status of the daemon.

%if "%{?vendor}" == "chum"
Title: Monit GUI
Type: desktop-application
PackagedBy: nephros
Categories:
 - System
 - Monitor
Custom:
  PackagingRepo: https://github.com/nephros/monit
  Repo: https://github.com/sailfishos-chum/monit
PackageIcon: https://mmonit.com/monit/img/logo.png
#        Screenshots:
#           - https://mmonit.com/monit/img/screenshots/1.png
#           - https://mmonit.com/monit/img/screenshots/9.png
#           - https://mmonit.com/monit/img/screenshots/10.png
#           - https://mmonit.com/monit/img/screenshots/2.png
#           - https://mmonit.com/monit/img/screenshots/4.png
#           - https://mmonit.com/monit/img/screenshots/5.png
Links:
  Homepage: https://www.mmonit.com/monit/slides
%endif


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# mangle version info
sed -i -e "s/unreleased/%{version}/" %{buildroot}%{_datadir}/%{name}/qml/%{name}.qml

# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%license LICENSE
%dir %{_datadir}/%{name}
%{_datadir}/%{name}/translations/*.qm
%{_datadir}/%{name}/qml/*
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/*/*/apps/%{name}.png
%{_datadir}/icons/*/*/apps/%{name}.svg
# >> files
# << files
