# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       monit-contrib

# >> macros
# << macros

Summary:    Community contributions for Monit
Version:    1.0.2310201
Release:    0
Group:      Applications
License:    CC0 and CC-BY-SA and ASL 2.0
BuildArch:  noarch
URL:        https://github.com/nephros/monit/
Source0:    %{name}-%{version}.tar.gz
Source100:  monit-contrib.yaml
Source101:  monit-contrib-rpmlintrc
Requires:   monit
BuildRequires:  make
Provides:   %{name} = 5.34.0
Obsoletes:   %{name} <= 5.34.0+git10

%description
%{summary}.

Configurations and scripts for Monit, created by the community.

Please submit your own scripts and config snippets to the packaging
repo so we can enhance the contrib package together.

%if "%{?vendor}" == "chum"
Title: Monit Community Configs
Type: console-application
PackagedBy: nephros
Categories:
 - System
 - Monitor
Custom:
  Repo: https://github.com/nephros/monit/
PackageIcon: https://mmonit.com/monit/img/logo.png
Links:
  Homepage: https://github.com/nephros/monit/tree/contrib/
  Help: https://mmonit.com/wiki/Monit/ConfigurationExamples
  Bugtracker: https://github.com/nephros/monit/issues
%endif


%prep
%setup -q -n %{name}-%{version}/contrib

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%config %{_sysconfdir}/monit.d/README.md
%dir %{_sysconfdir}/monit.d/scripts
%dir %{_sysconfdir}/monit.d/available
%config %{_sysconfdir}/monit.d/available/*.conf
%config %attr(750,root,root) %{_sysconfdir}/monit.d/scripts/*
# >> files
# << files
