# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       monit

# >> macros
# << macros

Summary:    Pro-active monitoring utility for unix systems
Version:    5.34.0
Release:    0
Group:      Applications
License:    AGPLv3+
URL:        https://mmonit.com/monit/dist/%{name}-%{version}.tar.gz
Source0:    %{name}-%{version}.tar.gz
Source1:    monitrc
Source2:    monit-web.desktop
Source100:  monit.yaml
Source101:  monit-rpmlintrc
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(libssl)
BuildRequires:  pkgconfig(libcrypt)
BuildRequires:  pam-devel
BuildRequires:  systemd
BuildRequires:  automake
BuildRequires:  autoconf
BuildRequires:  libtool
BuildRequires:  bison
BuildRequires:  flex
BuildRequires:  desktop-file-utils

%description
%{summary}.

%if "%{?vendor}" == "chum"
Please submit your scripts and config snippets to the packaging repo so we
can build a contrib package together.

Title: Monit
Type: console-application
PackagedBy: nephros
Categories:
 - System
 - Monitor
Custom:
  Repo: https://bitbucket.org/tildeslash/monit/
  PackagingRepo: https://github.com/nephros/monit/
PackageIcon: https://github.com/nephros/monit/raw/master/icons/Logo/Monit-Logo-512x512%401x.png
Links:
  Homepage: %{url}
  Help: https://mmonit.com/wiki/Monit
%endif


%prep
%setup -q -n %{name}-%{version}/monit

# >> setup
# << setup

%build
# >> build pre
./bootstrap
# << build pre

%configure --disable-static \
    --enable-optimized \
    --with-zlib

make %{?_smp_mflags}

# >> build post
# generate with correct paths
make system/startup/monit.service
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
rm -rf %{buildroot}%{_mandir}
rm -rf %{buildroot}%{_docdir}
install -m 600 -D %SOURCE1 %{buildroot}%{_sysconfdir}/monitrc
install -m 644 -D %SOURCE2 %{buildroot}%{_datadir}/applications/monit-web.desktop
install -m 644 -D system/startup/%{name}.service %{buildroot}/%{_unitdir}/%{name}.service
install -m 644 -D system/bash/%{name} %{buildroot}%{_sysconfdir}/bash_completion.d/%{name}
mkdir -p %{buildroot}%{_sysconfdir}/%{name}.d
for size in 76 512; do
install -m 644 -D ../icons/Icon/Monit-Icon-${size}x${size}@1x.png %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/%{name}.png
done
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%license COPYING
%{_bindir}/*
%{_unitdir}/%{name}.service
%{_datadir}/applications/%{name}-web.desktop
%{_datadir}/icons/hicolor/*/*/*.png
%config %{_sysconfdir}/bash_completion.d/%{name}
%config(noreplace) %{_sysconfdir}/monitrc
%dir %{_sysconfdir}/%{name}.d
# >> files
# << files
